# Generated by Django 4.2.4 on 2023-08-31 15:34

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="booking",
            field=mysite.models.ForeignKeyEx(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="mysite.booking",
            ),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="booking",
            field=mysite.models.ForeignKeyEx(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleanings",
                to="mysite.booking",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="apartment",
            field=mysite.models.ForeignKeyEx(
                db_column="apartment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apartment_contracts",
                to="mysite.apartment",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="owner",
            field=mysite.models.ForeignKeyEx(
                limit_choices_to={"role": "Owner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="tenant",
            field=mysite.models.ForeignKeyEx(
                limit_choices_to={"role": "Tenant"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=mysite.models.ForeignKeyEx(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="mysite.booking",
            ),
        ),
    ]
