# Generated by Django 4.2.4 on 2024-01-23 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_booking_tenants_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField()),
                ('sender_type', models.CharField(blank=True, choices=[('USER', 'USER'), ('SYSTEM', 'SYSTEM'), ('MANAGER', 'MANAGER'), ('GPT_GESS', 'GPT_GESS'), ('GPT_APPROVED', 'GPT_APPROVED')], db_index=True, max_length=32, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(blank=True, choices=[('NO_NEED_ACTION', 'NO_NEED_ACTION'), ('DB', 'DB'), ('KNOWLEDGE_BASE', 'KNOWLEDGE_BASE'), ('NOTIFICATION', 'NOTIFICATION')], db_index=True, default='NO_NEED_ACTION', max_length=32, null=True)),
                ('message_status', models.CharField(choices=[('ERROR', 'ERROR'), ('SENDED', 'SENDED'), ('NEED_ANSWERE', 'NEED_ANSWERE'), ('ANSWERED', 'ANSWERED')], db_index=True, default='SENDED', max_length=32)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='mysite.booking')),
            ],
        ),
    ]
