# Generated by Django 4.2.4 on 2023-09-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_remove_booking_period_remove_booking_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaning",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cleanings",
                to="mysite.booking",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to="mysite.booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="mysite.booking",
            ),
        ),
    ]
