# Generated by Django 4.2.4 on 2023-09-01 09:16

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_notification_booking_alter_cleaning_booking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="tenant",
        ),
        migrations.AddField(
            model_name="booking",
            name="assigned_cleaner",
            field=mysite.models.IntegerFieldEx(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="damage_deposit",
            field=mysite.models.DecimalFieldEx(
                blank=True, decimal_places=2, editable=False, max_digits=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="holding_deposit",
            field=mysite.models.DecimalFieldEx(
                blank=True, decimal_places=2, editable=False, max_digits=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="tenant_email",
            field=mysite.models.EmailFieldEx(
                blank=True, editable=False, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="tenant_full_name",
            field=mysite.models.CharFieldEx(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="tenant_phone",
            field=mysite.models.CharFieldEx(
                blank=True, editable=False, max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="booking",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract",
                to="mysite.booking",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="manager",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                limit_choices_to={"role": "Manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_apartments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="owner",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                limit_choices_to={"role": "Owner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_apartments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="booking",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleanings",
                to="mysite.booking",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="booking",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="mysite.booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="bank",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                limit_choices_to={"type": "Bank"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_payments",
                to="mysite.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="mysite.booking",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                limit_choices_to={"type": "Payment Method"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_methods_payments",
                to="mysite.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=mysite.models.CharFieldEx(
                choices=[
                    ("Income", "Income"),
                    ("Outcome", "Outcome"),
                    ("Damage Deposit", "Damage Deposit"),
                    ("Hold Deposit", "Hold Deposit"),
                    ("Booking", "Booking"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
