# Generated by Django 4.2.4 on 2024-02-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
