# Generated by Django 4.2.4 on 2023-09-01 10:34

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_remove_booking_contract_remove_contract_apartment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="tenant",
            field=mysite.models.ForeignKeyEx(
                blank=True,
                limit_choices_to={"role": "Tenant"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_id",
            field=mysite.models.CharFieldEx(default="", max_length=64),
        ),
    ]
