# Generated by Django 4.2.4 on 2023-08-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_bank_booking_paymentmethod_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sendInTelegram",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("pending", "Pending"),
                ],
                db_index=True,
                default="pending",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("scheduled", "Scheduled"), ("completed", "Completed")],
                db_index=True,
                default="scheduled",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("done", "Done"), ("pending", "Pending")],
                db_index=True,
                default="pending",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=14,
            ),
        ),
    ]
