# Generated by Django 4.2.4 on 2023-09-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0003_alter_cleaning_booking_alter_contract_booking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_notifications",
                to="mysite.booking",
            ),
        ),
    ]
