# Generated by Django 4.2.4 on 2023-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_alter_notification_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartment",
            old_name="room",
            new_name="apartment_n",
        ),
        migrations.AddField(
            model_name="booking",
            name="animals",
            field=models.CharField(
                blank=True,
                choices=[("Cat", "Cat"), ("Dog", "Dog"), ("Other", "Other")],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="other_tenants",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="visit_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tourism", "Tourism"),
                    ("Work", "Work"),
                    ("Medical", "Medical"),
                    ("Other", "Other"),
                ],
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Confirmed", "Confirmed"),
                    ("Canceled", "Canceled"),
                    ("Waiting Contract", "Waiting Contract"),
                    ("Waiting Payment", "Waiting Payment"),
                ],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Outcome", "Outcome"),
                    ("Damage Deposit", "Damage Deposit"),
                    ("Hold Deposit", "Hold Deposit"),
                    ("Damage Deposit Return", "Damage Deposit Return"),
                    ("Rent", "Rent"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
