# Generated by Django 4.2.4 on 2023-08-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_notification_sendintelegram_alter_booking_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="period",
            field=models.CharField(
                choices=[("dayly", "Dayly"), ("monthly", "Monthly")],
                db_index=True,
                default="dayly",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="scheduled",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="sign_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("done", "Done"),
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="pending",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("outcome", "Outcome"),
                    ("damage_deposit", "Damage Deposit"),
                    ("hold_deposit", "Hold Deposit"),
                ],
                db_index=True,
                default="pending",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                max_length=14,
            ),
        ),
    ]
