# Generated by Django 4.2.4 on 2023-09-01 14:32

from django.db import migrations
import mysite.models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_alter_booking_tenant_alter_contract_contract_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="sendInTelegram",
            new_name="send_in_telegram",
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=mysite.models.CharFieldEx(
                blank=True,
                choices=[
                    ("Confirmed", "Confirmed"),
                    ("Canceled", "Canceled"),
                    ("Pending", "Pending"),
                ],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
    ]
