# Generated by Django 4.2.4 on 2024-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_payment_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_model',
            field=models.CharField(
                default='', max_length=100, verbose_name='Car Model'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_price',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name='Car Price'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_rent_days',
            field=models.IntegerField(default=0, verbose_name='Car Rent Days'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_rent_car',
            field=models.BooleanField(
                default=False, verbose_name='Is Rent Car'),
        ),
    ]
