# Generated by Django 4.2.4 on 2024-03-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_booking_car_model_booking_car_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contract_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
