# Generated by Django 4.2.4 on 2023-09-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0005_rename_room_apartment_apartment_n_booking_animals_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartment",
            old_name="house_number",
            new_name="building_n",
        ),
        migrations.AddField(
            model_name="payment",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="mysite.apartment",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Outcome", "Outcome"),
                    ("Damage Deposit", "Damage Deposit"),
                    ("Hold Deposit", "Hold Deposit"),
                    ("Damage Deposit Return", "Damage Deposit Return"),
                    ("Rent", "Rent"),
                    ("Mortage", "Mortage"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
