# Generated by Django 4.2.4 on 2023-08-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0006_alter_booking_period_alter_booking_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_id",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("signed", "Signed"),
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
    ]
