# Generated by Django 4.2.4 on 2023-09-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0006_rename_house_number_apartment_building_n_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Confirmed", "Confirmed"),
                    ("Canceled", "Canceled"),
                    ("Waiting Contract", "Waiting Contract"),
                    ("Waiting Payment", "Waiting Payment"),
                ],
                db_index=True,
                default="Waiting Contract",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="visit_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tourism", "Tourism"),
                    ("Work", "Work"),
                    ("Medical", "Medical"),
                    ("Other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
