# Generated by Django 4.2.4 on 2024-04-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_booking_contract_send_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_rent_car',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Is Rent Car'),
        ),
    ]
