# Generated by Django 4.2.4 on 2023-08-21 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0007_contract_contract_id_contract_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cleaning",
            name="cleaner",
            field=models.ForeignKey(
                limit_choices_to={"role": "manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleanings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
