# Generated by Django 4.2.4 on 2023-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0008_paymentype_payment_payment_type_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentype",
            name="type",
            field=models.CharField(
                choices=[("In", "In"), ("Out", "Out")], db_index=True, max_length=32
            ),
        ),
    ]
