# Generated by Django 4.2.4 on 2023-08-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0008_cleaning_cleaner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="amount_bathrooms",
            new_name="bathrooms",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="amount_bedrooms",
            new_name="bedrooms",
        ),
        migrations.AlterField(
            model_name="booking",
            name="period",
            field=models.CharField(
                choices=[("Dayly", "Dayly"), ("Monthly", "Monthly")],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Confirmed", "Confirmed"),
                    ("Canceled", "Canceled"),
                    ("Pending", "Pending"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("Signed", "Signed"),
                    ("Pending", "Pending"),
                    ("Panceled", "Canceled"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("Done", "Done"),
                    ("Pending", "Pending"),
                    ("Canceled", "Canceled"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Outcome", "Outcome"),
                    ("Damage Deposit", "Damage Deposit"),
                    ("Hold Deposit", "Hold Deposit"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("In Management", "In Management"),
                    ("In Ownership", "In Ownership"),
                ],
                db_index=True,
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[("Available", "Available"), ("Unavailable", "Unavailable")],
                db_index=True,
                max_length=14,
            ),
        ),
    ]
