# Generated by Django 4.2.4 on 2024-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_booking_is_rent_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_rent_car',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Rent Car'),
        ),
    ]
