# Generated by Django 4.2.4 on 2024-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_booking_is_rent_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Merged', 'Merged')], db_index=True, default='Pending', max_length=32),
        ),
    ]
