# Generated by Django 4.2.4 on 2023-08-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0009_rename_amount_bathrooms_property_bathrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Cleaner", "Cleaner"),
                    ("Manager", "Manager"),
                    ("Tenant", "Tenant"),
                    ("Owner", "Owner"),
                ],
                max_length=14,
            ),
        ),
    ]
