# Generated by Django 4.2.4 on 2024-05-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='merged_payment_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
