# Generated by Django 4.2.4 on 2023-08-22 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0010_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Confirmed", "Confirmed"),
                    ("Canceled", "Canceled"),
                    ("Pending", "Pending"),
                ],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tenant",
            field=models.ForeignKey(
                limit_choices_to={"role": "Tenant"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="cleaner",
            field=models.ForeignKey(
                limit_choices_to={"role": "Cleaner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleanings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="Scheduled",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"role": "Owner"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("Signed", "Signed"),
                    ("Pending", "Pending"),
                    ("Panceled", "Canceled"),
                ],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="tenant",
            field=models.ForeignKey(
                limit_choices_to={"role": "Tenant"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("Done", "Done"),
                    ("Pending", "Pending"),
                    ("Canceled", "Canceled"),
                ],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Income", "Income"),
                    ("Outcome", "Outcome"),
                    ("Damage Deposit", "Damage Deposit"),
                    ("Hold Deposit", "Hold Deposit"),
                ],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="manager",
            field=models.ForeignKey(
                limit_choices_to={"role": "Manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                limit_choices_to={"role": "Owner"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
