# Generated by Django 4.2.4 on 2023-09-20 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0010_remove_payment_payment_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_type_model",
            new_name="payment_type",
        ),
    ]
