# Generated by Django 4.2.4 on 2023-09-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0011_rename_payment_type_model_payment_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="cleaning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cleaning_notifications",
                to="mysite.cleaning",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_notifications",
                to="mysite.payment",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Confirmed", "Confirmed"),
                    ("Waiting Contract", "Waiting Contract"),
                    ("Waiting Payment", "Waiting Payment"),
                ],
                db_index=True,
                default="Waiting Contract",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="cleaning",
            name="status",
            field=models.CharField(
                choices=[("Scheduled", "Scheduled"), ("Completed", "Completed")],
                db_index=True,
                default="Scheduled",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[("Signed", "Signed"), ("Pending", "Pending")],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("Done", "Done"), ("Pending", "Pending")],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Received", "Received")],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
    ]
