# Generated by Django 4.2.4 on 2024-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_payment_merged_payment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contract_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
