# Generated by Django 4.2.4 on 2023-08-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0011_alter_booking_status_alter_booking_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
