# Generated by Django 4.2.4 on 2023-09-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0012_notification_cleaning_notification_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
