# Generated by Django 4.2.4 on 2024-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_booking_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='visit_purpose',
            field=models.CharField(blank=True, choices=[('Tourism', 'Tourism'), ('Work Travel', 'Work Travel'), ('Medical', 'Medical'), ('House Repair', 'House Repair'), ('Relocation', 'Relocation'), ('Other', 'Other')], max_length=32),
        ),
    ]
