# Generated by Django 4.2.4 on 2024-06-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_booking_visit_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentype',
            name='balance_sheet_name',
            field=models.CharField(blank=True, choices=[('Receivables', 'Receivables'), ('Paybels', 'Paybels')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentype',
            name='category',
            field=models.CharField(blank=True, choices=[('Operating', 'Operating'), ('None Operating', 'None Operating')], db_index=True, max_length=50, null=True),
        ),
    ]
