# Generated by Django 4.2.4 on 2023-09-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0013_alter_notification_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                db_index=True,
                default="Pending",
                max_length=32,
            ),
        ),
    ]
