# Generated by Django 4.2.4 on 2023-09-22 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0014_alter_payment_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="status",
        ),
    ]
