# Generated by Django 4.2.4 on 2024-06-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_paymentype_balance_sheet_name_paymentype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
