# Generated by Django 4.2.4 on 2024-10-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_paymentype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Waiting Contract', 'Waiting Contract'), ('Waiting Payment', 'Waiting Payment'), ('Blocked', 'Blocked'), ('Pending', 'Pending')], db_index=True, default='Waiting Contract', max_length=32),
        ),
    ]
