# Generated by Django 4.2.4 on 2024-10-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_status',
            field=models.CharField(choices=[('ERROR', 'ERROR'), ('SENDED', 'SENDED')], db_index=True, default='SENDED', max_length=32),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message_type',
            field=models.CharField(blank=True, choices=[('NO_NEED_ACTION', 'NO_NEED_ACTION'), ('NEED_ACTION', 'NEED_ACTION'), ('DB', 'DB'), ('KNOWLEDGE_BASE', 'KNOWLEDGE_BASE'), ('NOTIFICATION', 'NOTIFICATION'), ('CONTRACT', 'CONTRACT')], db_index=True, default='NO_NEED_ACTION', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender_type',
            field=models.CharField(blank=True, choices=[('USER', 'USER'), ('MANAGER1', 'MANAGER1'), ('MANAGER2', 'MANAGER2'), ('GPT BOT', 'GPT BOT')], db_index=True, max_length=32, null=True),
        ),
    ]
