# Generated by Django 4.2.4 on 2024-10-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_alter_chat_message_status_alter_chat_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='twilio_conversation_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='twilio_message_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
