# Generated by Django 4.2.4 on 2023-10-02 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0018_alter_booking_visit_purpose"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contract",
        ),
    ]
