# Generated by Django 4.2.4 on 2024-10-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_chat_twilio_conversation_sid_chat_twilio_message_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Waiting Contract', 'Waiting Contract'), ('Waiting Payment', 'Waiting Payment'), ('Blocked', 'Blocked'), ('Pending', 'Pending'), ('Problem Booking', 'Problem Booking')], db_index=True, default='Waiting Contract', max_length=32),
        ),
    ]
