# Generated by Django 4.2.4 on 2023-10-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0019_delete_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Airbnb", "Airbnb"),
                    ("Referral", "Referral"),
                    ("Returning", "Returning"),
                    ("Other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
