# Generated by Django 4.2.4 on 2024-11-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
