# Generated by Django 4.2.4 on 2024-11-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_payment_keywords_payment_tenant_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
