# Generated by Django 4.2.4 on 2024-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_apartment_keywords_booking_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentype',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
