# Generated by Django 4.2.4 on 2024-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_paymentype_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandymanCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_phone', models.CharField(max_length=20)),
                ('apartment_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
