# Generated by Django 4.2.4 on 2024-12-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_handymancalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_number', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Booked', 'Booked')], max_length=255, null=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to='mysite.apartment')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_spots', to='mysite.booking')),
            ],
        ),
    ]
