# Generated by Django 4.2.4 on 2025-02-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_parking_parkingbooking_delete_apartmentparking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
