# Generated by Django 4.2.4 on 2025-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_parking_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
