# Generated by Django 4.2.4 on 2025-03-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_paymentmethod_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='payment_type_payments', to='mysite.paymentype'),
        ),
    ]
