# Generated by Django 4.2.4 on 2025-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_user_telegram_chat_id_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='associated_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
