# Generated by Django 4.2.4 on 2025-04-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_parking_associated_room_alter_parking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_notifications', to='mysite.apartment'),
        ),
    ]
