# Generated by Django 4.2.4 on 2025-04-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_notification_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='mysite.apartment'),
        ),
    ]
