# Generated by Django 4.2.4 on 2025-04-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_cleaning_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='raiting',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
