# Generated by Django 4.2.4 on 2025-04-24 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_handymanblockedslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymancalendar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handymancalendar',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='handymancalendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
