# Generated by Django 4.2.4 on 2025-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0035_handymancalendar_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='raiting',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
