# Generated by Django 4.2.4 on 2025-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0037_alter_parkingbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
