# Generated by Django 4.2.4 on 2025-06-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0038_apartment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='price',
        ),
        migrations.CreateModel(
            name='ApartmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(db_index=True, help_text='Date when this price becomes effective')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this price change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='mysite.apartment')),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('apartment', 'effective_date')},
            },
        ),
    ]
