# Generated by Django 4.2.4 on 2025-07-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0039_apartment_pricing_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
