# Generated by Django 4.2.4 on 2025-09-01 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0040_apartment_default_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_sid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('friendly_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_conversations', to='mysite.apartment')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_conversations', to='mysite.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TwilioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('webhook_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('messaging_binding_address', models.CharField(blank=True, max_length=20, null=True)),
                ('messaging_binding_proxy_address', models.CharField(blank=True, max_length=20, null=True)),
                ('message_timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mysite.twilioconversation')),
            ],
            options={
                'ordering': ['-message_timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
