# Generated by Django 4.2.4 on 2025-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0041_twilioconversation_twiliomessage_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lastUpdatedUser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
