# Generated by Django 4.2.4 on 2025-10-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0042_payment_lastupdateduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='lastUpdatedUser',
            new_name='last_updated_by',
        ),
    ]
