# Generated by Django 4.2.4 on 2025-11-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0043_rename_lastupdateduser_payment_last_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Car Model'),
        ),
    ]
