# Generated by Django 4.2.4 on 2025-11-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0046_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('sms', 'SMS/Messaging'), ('payment', 'Payment'), ('booking', 'Booking'), ('contract', 'Contract'), ('notification', 'Notification'), ('sync', 'Synchronization'), ('cleanup', 'Cleanup'), ('system', 'System'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('message', models.TextField()),
                ('context', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='mysite_syst_timesta_ddeb37_idx'), models.Index(fields=['category', '-timestamp'], name='mysite_syst_categor_64a030_idx'), models.Index(fields=['level', 'category', '-timestamp'], name='mysite_syst_level_e65c4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(db_index=True, max_length=255)),
                ('error_message', models.TextField()),
                ('context', models.CharField(db_index=True, max_length=500)),
                ('source', models.CharField(choices=[('web', 'Web Request'), ('api', 'API'), ('command', 'Management Command'), ('model', 'Model Operation'), ('task', 'Background Task'), ('webhook', 'Webhook'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('user_role', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('error_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('occurrences', models.IntegerField(default=1)),
                ('last_occurrence', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'severity'], name='mysite_erro_timesta_398b9b_idx'), models.Index(fields=['resolved', '-timestamp'], name='mysite_erro_resolve_7c2d37_idx'), models.Index(fields=['source', '-timestamp'], name='mysite_erro_source_eb57e9_idx'), models.Index(fields=['error_type', '-timestamp'], name='mysite_erro_error_t_98eb02_idx'), models.Index(fields=['username', '-timestamp'], name='mysite_erro_usernam_e6d9b0_idx'), models.Index(fields=['error_hash', '-last_occurrence'], name='mysite_erro_error_h_63d512_idx')],
            },
        ),
    ]
