# Generated by Django 4.2.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0047_systemlog_errorlog'),
    ]

    operations = [
        # This migration was intended for a payment constraint
        # but the original content was lost. Keeping as placeholder.
    ]



