# Generated by Django 4.2.4 on 2025-12-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0049_apartment_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='raiting',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
    ]
