# Generated by Django 4.2.4 on 2025-12-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0050_alter_apartment_raiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('note', models.TextField()),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notes', to='mysite.apartment')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='calendarnote',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='calendar_note_start_date_lte_end_date'),
        ),
    ]
