# Generated by Django 4.2.4 on 2025-12-31 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0051_calendarnote_and_more"),
        ("mysite", "0051_chat_message_template"),
    ]

    operations = []

