# Generated by Django 4.2.4 on 2026-01-20

from django.db import migrations, models
from django.db.models import Q


def null_apartment_when_booking_set(apps, schema_editor):
    Payment = apps.get_model("mysite", "Payment")
    Payment.objects.filter(booking__isnull=False, apartment__isnull=False).update(apartment=None)


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0052_merge_0051_calendarnote_and_chat_message_template"),
    ]

    operations = [
        migrations.RunPython(null_apartment_when_booking_set, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                name="payment_booking_or_apartment_not_both",
                check=Q(booking__isnull=True) | Q(apartment__isnull=True),
            ),
        ),
    ]

