# Generated by Django 4.2.4 on 2026-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0053_payment_booking_single_source_of_truth'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='knowledge_base',
            field=models.TextField(blank=True, null=True),
        ),
    ]
