# Generated by Django 4.2.4 on 2026-02-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0054_apartment_knowledge_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
