# Generated by Django 4.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0055_global_knowledge_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalknowledgebase',
            name='entry_type',
            field=models.CharField(choices=[('knowledge', 'Knowledge'), ('prompt', 'AI Prompt')], default='knowledge', max_length=20),
        ),
        migrations.AddField(
            model_name='globalknowledgebase',
            name='prompt_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='globalknowledgebase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
