# Generated by Django 4.2.4

from django.db import migrations


def seed_prompts(apps, schema_editor):
    GlobalKnowledgeBase = apps.get_model('mysite', 'GlobalKnowledgeBase')
    prompts = [
        {
            'name': 'AI Answer System Prompt',
            'entry_type': 'prompt',
            'prompt_key': 'ai_answer_system',
            'description': 'System prompt for AI tenant assistant. No placeholders.',
            'content': (
                "You are an AI assistant for a property management company. "
                "You help tenants in a group chat with questions about their apartment stay.\n\n"
                "For each tenant message, choose ONE of:\n"
                "1. ANSWER: You have enough info → give a concise, helpful answer (max 3 sentences).\n"
                "2. CLARIFY: You have relevant info about the topic but need one detail to answer precisely "
                "→ ask ONE short clarifying question.\n"
                "3. NO_ANSWER: You have no relevant info → respond ONLY with: NO_ANSWER\n\n"
                "RULES:\n"
                "- Never fabricate — only use facts from the context.\n"
                "- Be friendly and professional.\n"
                "- Answer in the same language as the tenant's message."
            ),
        },
        {
            'name': 'AI Answer User Prompt',
            'entry_type': 'prompt',
            'prompt_key': 'ai_answer_user',
            'description': 'User prompt for AI tenant assistant. Placeholders: {context}, {message_body}',
            'content': (
                "Context:\n{context}\n\n"
                "Tenant message: {message_body}\n\n"
                "Respond with an answer, a clarifying question, or NO_ANSWER."
            ),
        },
        {
            'name': 'AI Extract Check Prompt',
            'entry_type': 'prompt',
            'prompt_key': 'ai_extract_check',
            'description': 'Check if manager message has operational knowledge. Placeholders: {fields_ctx}, {message_body}',
            'content': (
                "You evaluate whether a manager's message contains OPERATIONAL knowledge "
                "about an apartment that should be saved in the free-text notes.\n\n"
                "The following information is ALREADY stored in structured database fields "
                "and must NOT be flagged as new — do not save it to notes:\n"
                "{fields_ctx}\n\n"
                "Only reply YES if the message contains new OPERATIONAL knowledge such as:\n"
                "- WiFi network name or password\n"
                "- Door/gate/lock access codes\n"
                "- Specific parking instructions\n"
                "- House rules (noise, pets, smoking, guests, etc.)\n"
                "- Appliance instructions or quirks\n"
                "- Local tips, nearby amenities\n"
                "- Any other operational detail NOT covered by the fields above\n\n"
                "Manager message: {message_body}\n\n"
                "Reply with YES or NO only."
            ),
        },
        {
            'name': 'AI Extract Merge Prompt',
            'entry_type': 'prompt',
            'prompt_key': 'ai_extract_merge',
            'description': 'Merge new info into apartment knowledge base. Placeholders: {knowledge_base}, {message_body}',
            'content': (
                "Current knowledge base:\n{knowledge_base}\n\n"
                "New information to add: {message_body}\n\n"
                "Merge the new information into the knowledge base. Keep it clear and organized.\n"
                "Return ONLY the updated knowledge base text, nothing else."
            ),
        },
    ]
    for p in prompts:
        if not GlobalKnowledgeBase.objects.filter(prompt_key=p['prompt_key']).exists():
            GlobalKnowledgeBase.objects.create(**p)


def reverse_seed(apps, schema_editor):
    GlobalKnowledgeBase = apps.get_model('mysite', 'GlobalKnowledgeBase')
    GlobalKnowledgeBase.objects.filter(
        prompt_key__in=['ai_answer_system', 'ai_answer_user', 'ai_extract_check', 'ai_extract_merge']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0056_global_kb_prompt_fields'),
    ]

    operations = [
        migrations.RunPython(seed_prompts, reverse_seed),
    ]
