# Generated by Django 4.2.4 on 2026-03-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0057_seed_ai_prompts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('knowledge', 'Knowledge'), ('prompt', 'AI Prompt'), ('ai_model', 'AI Model')], default='knowledge', max_length=20)),
                ('prompt_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalKnowledgeBase',
        ),
    ]
