# Generated by Django 4.2.4 on 2026-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0058_aimanagement_delete_globalknowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliomessage',
            name='ai_kb_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliomessage',
            name='ai_kb_updated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliomessage',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliomessage',
            name='ai_sent_to_chat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliomessage',
            name='forwarded_to_group_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
