# Generated by Django 4.2.4 on 2026-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0059_twilimessage_ai_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimanagement',
            name='entry_type',
            field=models.CharField(choices=[('knowledge', 'Knowledge'), ('prompt', 'AI Prompt'), ('ai_model', 'AI Model'), ('sms_template', 'SMS Template')], default='knowledge', max_length=20),
        ),
    ]
