# Generated by Django 4.2.4 on 2026-03-05 17:37

from django.db import migrations, models


def set_entry_types_and_sms_enabled(apps, schema_editor):
    AIManagement = apps.get_model('mysite', 'AIManagement')
    chat_template_keys = ['contract_signed_message', 'contract_message_template', 'welcome_message_template']
    sms_notification_keys = [
        'move_in', 'unsigned_contract_1d', 'unsigned_contract_3d', 'unsigned_contract_7d',
        'pending_rent_3d', 'deposit_reminder', 'due_payment', 'extension', 'move_out', 'safe_travel'
    ]
    AIManagement.objects.filter(
        prompt_key__in=chat_template_keys, entry_type='prompt'
    ).update(entry_type='sms_template', sms_enabled=None)
    AIManagement.objects.filter(
        entry_type='sms_template', prompt_key__in=sms_notification_keys
    ).update(sms_enabled=True)
    AIManagement.objects.filter(entry_type='sms_template', sms_enabled__isnull=True).exclude(
        prompt_key__in=sms_notification_keys
    ).update(sms_enabled=None)


def reverse_set_entry_types_and_sms_enabled(apps, schema_editor):
    AIManagement = apps.get_model('mysite', 'AIManagement')
    chat_template_keys = ['contract_signed_message', 'contract_message_template', 'welcome_message_template']
    AIManagement.objects.filter(
        prompt_key__in=chat_template_keys, entry_type='sms_template'
    ).update(entry_type='prompt')
    AIManagement.objects.update(sms_enabled=None)


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0060_alter_aimanagement_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimanagement',
            name='sms_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(set_entry_types_and_sms_enabled, reverse_set_entry_types_and_sms_enabled),
    ]
