# Generated by Django 4.2.4 on 2026-03-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0061_add_sms_enabled_to_aimanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, help_text='External platform booking id (e.g. Rental Guru)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(blank=True, choices=[('Airbnb', 'Airbnb'), ('Referral', 'Referral'), ('Returning', 'Returning'), ('Rental Guru', 'Rental Guru'), ('Other', 'Other')], help_text='External platform (e.g. Rental Guru)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, help_text='External platform payment id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(blank=True, choices=[('Airbnb', 'Airbnb'), ('Referral', 'Referral'), ('Returning', 'Returning'), ('Rental Guru', 'Rental Guru'), ('Other', 'Other')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source', 'source_id'), name='payment_source_source_id_uniq'),
        ),
    ]
