# Generated by Django 4.2.4 on 2026-09-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0077_kb_check_suggested_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Waiting Contract', 'Waiting Contract'), ('Waiting Payment', 'Waiting Payment'), ('Blocked', 'Blocked'), ('Pending', 'Pending'), ('Problem Booking', 'Problem Booking'), ('Cancelled', 'Cancelled')], db_index=True, default='Waiting Contract', max_length=32),
        ),
    ]
