# Generated by Django 4.2.4 on 2026-09-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0082_apartment_ai_group_chat_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TENANT_MESSAGE', 'Tenant message'), ('STAFF_MESSAGE', 'Staff message'), ('CLICKUP_MESSAGE', 'ClickUp message'), ('FOLLOWUP_DUE', 'Follow-up due'), ('TICKET_UPDATE', 'Ticket update')], db_index=True, default='TENANT_MESSAGE', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('send_allowed', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_events', to='mysite.twilioconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_events', to='mysite.twiliomessage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(default='TENANT_MESSAGE', max_length=30)),
                ('mode', models.CharField(choices=[('live', 'Live (sent to group chat)'), ('test', 'Test (stored only)')], default='test', max_length=10)),
                ('backend', models.CharField(default='claude_cli', max_length=30)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('why', models.TextField(blank=True, null=True)),
                ('no_answer', models.BooleanField(default=False)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('sent_to_chat', models.BooleanField(default=False)),
                ('delivery_note', models.CharField(blank=True, max_length=255, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('num_turns', models.PositiveIntegerField(default=0)),
                ('tool_calls', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('report_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='mysite.aievent')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='mysite.twiliomessage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='aievent',
            index=models.Index(fields=['status', 'id'], name='mysite_aiev_status_f259f7_idx'),
        ),
    ]
