# Generated by Django 4.2.4 on 2026-09-21 11:46

from django.db import migrations, models
import django.db.models.deletion


# Staff the AI agent knows about (confirmed by the user 2026-09-21; ClickUp ids from
# claude_code_integration_doc/clickup_users.json). Edit later on /ai-staff/.
STAFF = [
    # ai_name, full_name, role, phone, secondary_phone, clickup_user_id
    ('Edy', 'Farouk Ahmed', 'operations', None, None, '176673799'),
    # Supervisor role from the AI prompt: the person is not decided yet
    ('Kevin', None, 'supervisor', None, None, None),
    ('Janna', 'Janna', 'accounting', '+15618438867', None, '118004539'),
    ('Farid', 'Farid Gazizov', 'owner', '+15614603904', '+15612205252', '126173964'),
    ('Andrei', 'Andrei Vaulin', 'engineering', None, None, '89595503'),
]


def seed_staff(apps, schema_editor):
    StaffMember = apps.get_model('mysite', 'StaffMember')
    for ai_name, full_name, role, phone, secondary_phone, clickup_user_id in STAFF:
        StaffMember.objects.get_or_create(ai_name=ai_name, defaults={
            'full_name': full_name, 'role': role, 'phone': phone, 'secondary_phone': secondary_phone,
            'clickup_user_id': clickup_user_id,
            'created_by': 'migration 0084', 'last_updated_by': 'migration 0084',
        })


def unseed_staff(apps, schema_editor):
    apps.get_model('mysite', 'StaffMember').objects.filter(created_by='migration 0084').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0083_ai_agent_events_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_name', models.CharField(help_text='Name the AI uses for this person, e.g. Edy', max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner of the company'), ('operations', 'Property manager (operations, maintenance, tenant requests)'), ('supervisor', 'Supervisor (escalations, sensitive matters)'), ('accounting', 'Accounting (payments, deposits, refunds)'), ('engineering', 'Engineering (AI / system errors)'), ('staff', 'Other authorized staff')], default='staff', max_length=20)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('secondary_phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('clickup_user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ai_name'],
            },
        ),
        migrations.CreateModel(
            name='AIIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('WAITING_FOR_TENANT', 'Waiting for tenant'), ('WAITING_FOR_EDY', 'Waiting for Edy'), ('WAITING_FOR_JANNA', 'Waiting for Janna'), ('WAITING_FOR_KEVIN', 'Waiting for Kevin'), ('STAFF_HANDLING', 'Staff handling'), ('MAINTENANCE_OPEN', 'Maintenance open'), ('WAITING_FOR_TENANT_CONFIRMATION', 'Waiting for tenant confirmation'), ('ESCALATED_SENSITIVE', 'Escalated (sensitive)'), ('RESOLVED', 'Resolved')], db_index=True, default='WAITING_FOR_EDY', max_length=40)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=10)),
                ('ticket_title', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(default='test', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_issues', to='mysite.apartment')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_issues', to='mysite.booking')),
                ('created_by_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to='mysite.airun')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AIFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('kind', models.CharField(choices=[('tenant_nudge', 'Tenant nudge'), ('second_tenant_nudge', 'Second tenant nudge'), ('staff_reminder', 'Staff reminder'), ('escalation_check', 'Escalation check')], max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fired', 'Fired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('status_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to='mysite.airun')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='mysite.aiissue')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='AICaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('text', models.TextField()),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_case_notes', to='mysite.booking')),
                ('created_by_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_notes', to='mysite.airun')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes', to='mysite.aiissue')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RunPython(seed_staff, unseed_staff),
    ]
