# Generated by Django 4.2.4 on 2026-09-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0084_ai_agent_issues_followups_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('apartment', 'Apartment'), ('building', 'Building'), ('company', 'Company')], db_index=True, default='apartment', max_length=10)),
                ('building', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('knowledge_type', models.CharField(choices=[('fact', 'Fact'), ('policy', 'Policy')], default='fact', max_length=10)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.TextField()),
                ('confidence', models.CharField(choices=[('verified', 'Verified'), ('candidate', 'Candidate (needs a manager)')], db_index=True, default='candidate', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Replaced by a newer entry'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=10)),
                ('is_access_code', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_knowledge', to='mysite.apartment')),
                ('created_by_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge', to='mysite.airun')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
