# Generated by Django 4.2.4 on 2026-09-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0085_ai_agent_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='airun',
            name='review_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
