# Generated by Django 4.2.4 on 2026-09-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0086_airun_review_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClickUpChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('list_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_clickup', to='mysite.apartment')),
            ],
        ),
    ]
