# Generated by Django 4.2.4 on 2026-09-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0087_ai_clickup_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='ai_clickup_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='ai_clickup_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='ai_clickup_list_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='ai_clickup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
