# Generated by Django 4.2.4 on 2026-09-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0088_apartment_ai_clickup_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIClickUpChannel',
        ),
    ]
