# Generated by Django 4.2.4 on 2026-09-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0089_remove_ai_clickup_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('send_after', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
