# Generated by Django 4.2.4 on 2026-09-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0090_pending_outbound_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='airun',
            name='final_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airun',
            name='hold_status',
            field=models.CharField(blank=True, choices=[('holding', 'Waiting for staff review'), ('sent', 'Sent as written'), ('corrected', 'Corrected by staff and sent'), ('cancelled', 'Cancelled by staff'), ('superseded', 'Replaced by a newer answer'), ('suppressed', 'Staff answered directly'), ('failed', 'Send failed'), ('test', 'Test mode')], db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='airun',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airun',
            name='review',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='airun',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiknowledge',
            name='knowledge_type',
            field=models.CharField(choices=[('fact', 'Fact'), ('policy', 'Policy'), ('lesson', 'Answer lesson')], default='fact', max_length=10),
        ),
    ]
