# Generated by Django 4.2.4 on 2026-09-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0092_user_phone_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioMessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_sid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('download_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='mysite.twiliomessage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
