# Generated by Django 4.2.4 on 2026-09-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0095_knowledge_documents_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiissue',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='handled_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='handled_prev_state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='last_tenant_ask_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='next_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='stage',
            field=models.CharField(default='reported', max_length=20),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='stage_times',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='telegram_thread_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='tenant_asks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiissue',
            name='tenant_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airun',
            name='triage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pendingoutboundmessage',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aifollowup',
            name='kind',
            field=models.CharField(choices=[('tenant_nudge', 'Tenant nudge'), ('second_tenant_nudge', 'Second tenant nudge'), ('staff_reminder', 'Staff reminder'), ('escalation_check', 'Escalation check'), ('deadline_reminder', 'Before a tenant deadline')], max_length=30),
        ),
        migrations.CreateModel(
            name='AIAlertCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('staff_name', models.CharField(max_length=50)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('phone_index', models.PositiveIntegerField(default=0)),
                ('call_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Calling'), ('answered', 'Answered'), ('unanswered', 'Not answered'), ('failed', 'Failed'), ('simulated', 'Simulated'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('check_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(default='test', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_calls', to='mysite.airun')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_calls', to='mysite.aievent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AIAfterHoursAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_sid', models.CharField(db_index=True, max_length=100)),
                ('mode', models.CharField(default='test', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('would_send', 'Would send (test)'), ('suppressed', 'Suppressed'), ('not_applicable', 'Not applicable'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='after_hours_ack', to='mysite.aievent')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
