"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (gunicorn cwd may differ from BASE_DIR).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"],

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ["DEBUG"] or False

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = 'mysite.User'
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'

# ENABLE_DYNAMIC_MODEL_FIELDS = True

os.makedirs(BASE_DIR / "logs", exist_ok=True)
# Each file log rotates at 20 MB and keeps 5 old files (common.log.1 ... common.log.5).
LOG_FILE_MAX_BYTES = 20 * 1024 * 1024
LOG_FILE_BACKUP_COUNT = 5
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'exclude_404': {
            '()': 'mysite.logging_filters.Exclude404Filter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'jsonl': {
            'format': '{message}',
            'style': '{',
        },
    },
    'handlers': {
       
        'common': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': LOG_FILE_MAX_BYTES,
            'backupCount': LOG_FILE_BACKUP_COUNT,
            'filename': 'logs/common.log',
            'formatter': 'verbose',
            'filters': ['exclude_404'],
        },
        'debug': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': LOG_FILE_MAX_BYTES,
            'backupCount': LOG_FILE_BACKUP_COUNT,
            'filename': 'logs/debug.log',
            'formatter': 'verbose',
        },
        'payment_sync_v2_trace': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': LOG_FILE_MAX_BYTES,
            'backupCount': LOG_FILE_BACKUP_COUNT,
            'filename': str(BASE_DIR / 'logs' / 'payment_sync_v2_trace.jsonl'),
            'formatter': 'jsonl',
        },
        'group_chat_log': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': LOG_FILE_MAX_BYTES,
            'backupCount': LOG_FILE_BACKUP_COUNT,
            'filename': str(BASE_DIR / 'logs' / 'group_chat_log.log'),
            'formatter': 'jsonl',
        },
    },
    'loggers': {
        'mysite.debug': {
            'handlers': ['debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'mysite.common': {
            'handlers': ['common'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'mysite.payment_sync_v2_trace': {
            'handlers': ['payment_sync_v2_trace'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'mysite.group_chat_log': {
            'handlers': ['group_chat_log'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['common'],
        'level': 'WARNING',
    },
}

# Application definition
# CSRF_COOKIE_DOMAIN = '127.0.0.1'


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    "mysite",
    "widget_tweaks",
    'compressor',
    'slippers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mysite.request_context_middleware.RequestContextMiddleware',  # Track current user
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'mysite.error_handling_middleware.GlobalErrorHandlingMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

# SESSION_COOKIE_SAMESITE = None
# CSRF_COOKIE_SAMESITE = None
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                # 'django.template.context_processors.csrf',
                'mysite.context_processors.current_user_context',
                'django.contrib.messages.context_processors.messages',
            ],
            "builtins": ["slippers.templatetags.slippers"],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ["PGDATABASE"],
        'USER': os.environ["PGUSER"],
        'PASSWORD': os.environ["PGPASSWORD"],
        'HOST': os.environ["PGHOST"],
        'PORT': os.environ["PGPORT"],
    }
}
# print(DATABASES, "DATABASES")  # Commented out to prevent password leakage in logs

APPEND_SLASH = False

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# Compression for tailwind
COMPRESS_ROOT = BASE_DIR / 'static'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Photos/files received in Twilio Conversations (served only via the login-protected chat view)
TWILIO_MEDIA_DIR = os.path.join(BASE_DIR, "data", "twilio_media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
