from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', views.custom_login_view, name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('users/', views.users, name='users'),
    path('apartments/', views.apartments, name='apartments'),
    path('apartmentprice/', views.apartment_prices, name='apartment_prices'),
    path('apartment/', views.apartment, name='apartment'),
    path('apartments_analytics/', views.apartments_analytics,
         name='apartments_analytics'),
    path('cleanings/', views.cleanings, name='cleanings'),
    path('bookings/', views.bookings, name='bookings'),
    path('payments/', views.payments, name='payments'),
    path('notifications/', views.notifications, name='notifications'),
    path('paymentmethods/', views.payment_methods, name='paymentmethods'),
    path('paymenttypes/', views.payment_types, name='paymenttypes'),
    path('notifications/', views.notifications, name='notifications'),
    path('docuseal-callback/', views.docuseal_callback, name='docuseal_callback'),
    path('payment-report/', views.paymentReport, name='paymentReport'),
    path('conversation-created-webhook/', views.twilio_webhook, name='twilio_webhook'),
    path('generate-invoice/', views.generate_invoice, name='generateInvoice'),
    path('booking-report/', views.booking_report, name='booking_report'),
    path('apartment-report/', views.apartment_report, name='apartment_report'),
    path('payments-sync/', views.sync_payments, name='sync_payments'),
    path('payments-sync-v2/', views.sync_payments_v2, name='sync_payments_v2'),
    path('payments-sync-v2/fetch-db-payments/', views.fetch_db_payments_for_matching, name='fetch_db_payments_for_matching'),
    path('payments-sync-v2/match-selection/', views.match_selection_v2, name='match_selection_v2'),
    path('payments-sync-v2/fetch-merged-db-payments/', views.fetch_merged_db_payments_for_file, name='fetch_merged_db_payments_for_file'),
    path('booking-availability/', views.booking_availability, name='booking_availability'),
    path('create-booking/', views.create_booking_by_link, name='create_booking_by_link'),
    path('handyman_calendar/', views.handyman_calendar, name='handyman_calendar'),
    path('parking_calendar/', views.parking_calendar, name='parking_calendar'),
    path('api/apartment-booking-dates/', views.ApartmentBookingDates.as_view(), name='apartment_booking_dates'),
    path('api/calendar-notes/', views.create_calendar_note, name='create_calendar_note'),
    path('api/calendar-notes/list/', views.list_calendar_notes, name='list_calendar_notes'),
    path('api/calendar-notes/<int:note_id>/update/', views.update_calendar_note, name='update_calendar_note'),
    path('api/calendar-notes/<int:note_id>/delete/', views.delete_calendar_note, name='delete_calendar_note'),
    path('api/update-apartment-price-by-rooms/', views.UpdateApartmentPriceByRooms.as_view(), name='update_apartment_price_by_rooms'),
    path('api/update-single-apartment-price/', views.UpdateSingleApartmentPrice.as_view(), name='update_single_apartment_price'),
    path('api/bookings/', views.RentalGuruCreateBookingAPI.as_view(), name='api_rental_guru_create_booking'),
    path('api/bookings/<int:pk>/', views.RentalGuruUpdateBookingAPI.as_view(), name='api_rental_guru_update_booking'),
    path('api/bookings/by-source-id/<str:source_id>/', views.RentalGuruUpdateBookingBySourceIdAPI.as_view(), name='api_rental_guru_update_booking_by_source_id'),
    path('api/payments/', views.RentalGuruCreatePaymentAPI.as_view(), name='api_rental_guru_create_payment'),
    path('api/payments/<int:pk>/', views.RentalGuruUpdatePaymentAPI.as_view(), name='api_rental_guru_update_payment'),
    # Chat interface URLs
    path('chat/', views.chat_list, name='chat_list'),
    path('chat/export.md/', views.export_group_chats_md, name='export_group_chats_md'),
    path('chat/<str:conversation_sid>/', views.chat_detail, name='chat_detail'),
    path('chat/<str:conversation_sid>/send/', views.send_message, name='send_message'),
    path('chat/<str:conversation_sid>/delete-all-messages/', views.delete_all_chat_messages, name='delete_all_chat_messages'),
    path('chat/<str:conversation_sid>/delete/', views.delete_chat_conversation, name='delete_chat_conversation'),
    path('chat/<str:conversation_sid>/knowledge-base/', views.update_chat_knowledge_base, name='update_chat_knowledge_base'),
    path('chat/<str:conversation_sid>/knowledge-base/generate/', views.generate_chat_knowledge_base, name='generate_chat_knowledge_base'),
    path('chat/knowledge-base-prompts/<str:prompt_key>/', views.knowledge_base_prompt, name='knowledge_base_prompt'),
    path('chat/<str:conversation_sid>/apartment-kb/', views.update_chat_apartment_kb, name='update_chat_apartment_kb'),
    path('chat/<str:conversation_sid>/notes/', views.update_conversation_notes, name='update_conversation_notes'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/delete/', views.delete_chat_message, name='delete_chat_message'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/generate-ai-answer/', views.generate_message_ai_answer, name='generate_message_ai_answer'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/answer-rule/', views.answer_rule_context, name='answer_rule_context'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/answer-rule/generate/', views.generate_answer_rule, name='generate_answer_rule'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/answer-rule/save/', views.save_answer_rule, name='save_answer_rule'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/kb-rule/', views.kb_rule_context, name='kb_rule_context'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/kb-rule/generate/', views.generate_kb_rule, name='generate_kb_rule'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/kb-rule/save/', views.save_kb_rule, name='save_kb_rule'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/notes/', views.update_message_notes, name='update_message_notes'),
    path('chat/<str:conversation_sid>/generate-ai-answers/', views.generate_all_customer_ai_answers_view, name='generate_all_customer_ai_answers'),
    path('chat/<str:conversation_sid>/load-more/', views.load_more_messages, name='load_more_messages'),
    path('chat/templates/', views.chat_template_list, name='chat_template_list'),
    path('chat/templates/create/', views.chat_template_create, name='chat_template_create'),
    # AI Management
    path('ai-management/', views.ai_management_view, name='ai_management'),
    path('globalknowledgebase/', RedirectView.as_view(url='/ai-management/', permanent=True)),
    # AI agent (Claude) runs and reports
    path('ai-runs/', views.ai_runs_view, name='ai_runs'),
    path('ai-runs/<int:run_id>/', views.ai_run_detail_view, name='ai_run_detail'),
    path('chat/<str:conversation_sid>/messages/<int:message_id>/ai-agent-status/', views.ai_agent_message_status, name='ai_agent_message_status'),
    # Database Activity Monitoring
    path('database-activity/', views.database_activity, name='database_activity'),

]

